#!/usr/bin/env bash

# cd into folder where the driver is located, or quit (defensive)
# http://stackoverflow.com/questions/3349105
cd "${0%/*}" || exit 1

echo "In: $(pwd)"

indent4() {
  sed -e 's/^/    /'
}
indent8() {
  sed -e 's/^/        /'
}

# Helper colors
cnone="$(echo -ne '\033[0m')"
cwhiteb="$(echo -ne '\033[1;37m')"
cred="$(echo -ne '\033[0;31m')"
cgreen="$(echo -ne '\033[0;32m')"

# Detects whether we can add colors or not
# http://stackoverflow.com/a/911213
in_white() {
  [ -t 1 ] && echo -n "$cwhiteb"
  cat -
  [ -t 1 ] && echo -n "$cnone"
}
in_red() {
  [ -t 1 ] && echo -n "$cred"
  cat -
  [ -t 1 ] && echo -n "$cnone"
}
in_green() {
  [ -t 1 ] && echo -n "$cgreen"
  cat -
  [ -t 1 ] && echo -n "$cnone"
}

meet_parents=0
make_friends=0
revert_mistakes=0
get_married=0
total_passed=0

check_if_tracked() {
  local file="$1"

  if git ls-files --error-unmatch "$file" &> /dev/null; then
    return 0
  fi

  return 1
}

failed_with_message() {
  local message="$1"
  echo "    Lab incomplete." | in_red

  echo "    $message"
}

pass_with_message() {
  local message="$1"
  echo "    Passed: $message." | in_green
  echo
}

check_current_branch_name() {
  local branch="$1"
  local actualBranch
  actualBranch="$(git rev-parse --abbrev-ref HEAD)"

  if [ "$actualBranch" != "$branch" ]; then
    return 1
  fi
}

check_phase_1() {
  check_if_tracked "meet-parents.md"
  if [ "$?" -ne 0 ]; then
    check_current_branch_name "Taylor"
    if [ "$?" -eq 0 ]; then
      failed_with_message "    It looks like you're on Taylor, but you haven't merged Charlie in just yet. You are missing meet-parents.md"
      total_passed=3
      meet_parents=1
      make_friends=1
      revert_mistakes=1
      return 1
    fi
    failed_with_message "    meet-parents.md must be tracked by git. Make sure you added and committed it."
    return 1
  fi
}

check_phase_2() {
  check_phase_1
  if [ "$?" -ne 0 ]; then
    return 1
  fi

  check_if_tracked "make-friends.md"
  if [ "$?" -ne 0 ]; then
    failed_with_message "    make-friends.md must be tracked by git. Make sure you added and committed it."
    return 1
  fi
}

check_phase_3() {
  check_if_tracked "meet-parents.md"
  if [ "$?" -ne 0 ]; then

    check_current_branch_name "Taylor"
    if [ "$?" -eq 0 ]; then
      failed_with_message "    It looks like you're on Taylor, but you havent merged all of Charlie in just yet. You are missing meet-parents.md"
      total_passed=3
      meet_parents=1
      make_friends=1
      revert_mistakes=1
      return 1
    fi

    failed_with_message "    meet-parents.md must be tracked by git. Make sure you added and committed it."
    return 1
  fi

  check_if_tracked "make-friends.md"
  if [ "$?" -ne 0 ]; then

    check_current_branch_name "Taylor"
    if [ "$?" -eq 0 ]; then
      failed_with_message "    It looks like you're on Taylor, but you havent merged all of Charlie in just yet. You are missing make-friends.md"
      total_passed=3
      meet_parents=1
      make_friends=1
      revert_mistakes=1
      return 1
    fi

    failed_with_message "    make-friends.md must be tracked by git. Make sure you added and committed it."
    return 1
  fi

  check_if_tracked "infidelity.md"
  if [ "$?" -ne 1 ]; then

    check_current_branch_name "Taylor"
    if [ "$?" -eq 0 ]; then
      failed_with_message "    It looks like you're on Taylor, but you havent merged all of Charlie in just yet. You still have infidelity.md"
      total_passed=3
      meet_parents=1
      make_friends=1
      revert_mistakes=1
      return 1
    fi

    failed_with_message "    infidelity.md must be reverted. Check out documentation on git revert."
    return 1
  fi
}

check_phase_4() {
  check_current_branch_name "Taylor"
  if [ "$?" -ne 0 ]; then
    failed_with_message "    You don't seem to be on the correct branch. You should be on Taylor."
    return 1
  fi

  check_phase_3
}

pushd ../story-labs &> /dev/null

check_phase_1
if [ "$?" -eq 0 ]; then
  meet_parents=1
  pass_with_message "meet parents"
  ((++total_passed))
  check_phase_2
  if [ "$?" -eq 0 ]; then
    make_friends=1
    pass_with_message "make friends"
    ((++total_passed))
    check_phase_3
    if [ "$?" -eq 0 ]; then
      revert_mistakes=1
      pass_with_message "revert mistakes"
      ((++total_passed))
      check_phase_4
      if [ "$?" -eq 0 ]; then
	get_married=1
	pass_with_message "get married"
	((++total_passed))
	rm ../final-story.md &> /dev/null
	touch ../final-story.md

	{ cat ../driver/intro.md; cat meet-parents.md; cat ../driver/meet-ashley.md;
	cat make-friends.md; cat ../driver/conclusion.md; } >> ../final-story.md
      fi
    fi
  fi
fi

popd &> /dev/null

tests_failed=$((4-total_passed))

echo
echo "Finished."
echo "Tests passed: $total_passed"
echo "Tests failed: $tests_failed"
echo "Tests total:  4"
echo
echo "{\"scores\": {\"meet parents\": $meet_parents, \"make friends\": $make_friends, \"revert mistakes\": $revert_mistakes, \"get married\": $get_married}}"
