#!/usr/bin/env bash

# This script checks your solution against our reference solution.

driver_dir="$(dirname "$0")"

cd "$driver_dir" || exit

indent4() {
  sed -e 's/^/    /'
}
indent8() {
  sed -e 's/^/        /'
}
list_dir() {
  if which tree &> /dev/null; then
    pushd "$@" &> /dev/null
    tree -F --dirsfirst .
    popd &> /dev/null
  else
    pushd "$@" &> /dev/null
    find . | sort
    popd &> /dev/null
  fi
}

# Helper colors
cnone="$(echo -ne '\033[0m')"
cwhiteb="$(echo -ne '\033[1;37m')"
cred="$(echo -ne '\033[0;31m')"
cgreen="$(echo -ne '\033[0;32m')"

# Detects whether we can add colors or not
# http://stackoverflow.com/a/911213
in_white() {
  [ -t 1 ] && echo -n "$cwhiteb"
  cat -
  [ -t 1 ] && echo -n "$cnone"
}
in_red() {
  [ -t 1 ] && echo -n "$cred"
  cat -
  [ -t 1 ] && echo -n "$cnone"
}
in_green() {
  [ -t 1 ] && echo -n "$cgreen"
  cat -
  [ -t 1 ] && echo -n "$cnone"
}

scores=""

check_doesnt_cheat() {
  local file=$1

 if grep -q cat "$file"; then
   echo "    You seem to be using 'cat' in your solution. This is not valid for this lab." | in_red
   return 1
 fi

 if grep -q echo "$file"; then
   echo "    You seem to be using 'echo' in your solution. This is not valid for this lab." | in_red
   return 1
 fi

}

check_if_executable() {
  local file="$1"

  if [ ! -f "$file" ]; then
    echo "    $file does not exist." | in_red
    return 1
  fi

  if [ ! -x "$file" ]; then
    echo "    $file does not have executable permissions." | in_red
    return 1
  fi

  if ! head -n 1 "$file" | grep '#!/.*bash' &> /dev/null; then
    echo "    $file does not have a shebang." | in_red
    return 1
  fi
}

function fail_test {
    local test_name="$1"

    ((++tests_failed))
    scores=$scores"\"$test_name\": 0"
}

scores=""

tests_passed=0
tests_failed=0
function check_solution {
  local test_name=$1
  local theirs=$2
  local ours=$3
  local should_sort=$4

  echo "Testing $theirs..." | in_white
  # Before || is for GNU mktemp, after || is for OS X
  temp_file_theirs=$(mktemp 2> /dev/null || mktemp -t tmp)
  temp_file_ours=$(mktemp 2> /dev/null || mktemp -t tmp)

  # cd into folder with student's code, then cd back here after
  pushd .. &> /dev/null
  check_if_executable "./$theirs"
  good_executable="$?"
  if [ $good_executable -ne 0 ]; then
    popd &> /dev/null
    fail_test "$test_name"
    return
  fi

  check_doesnt_cheat "./$theirs"
  doesnt_cheat="$?"
  if [ $doesnt_cheat -ne 0 ]; then
    popd &> /dev/null
    fail_test "$test_name"
    return
  fi

  if [ $should_sort -eq 1 ]; then
    "./$theirs" | sort > "$temp_file_theirs"
  else
    "./$theirs" > "$temp_file_theirs"
  fi
  popd &> /dev/null

  if [ $should_sort -eq 1 ]; then
    sort "$ours" > "$temp_file_ours"
  else
    cp "$ours" "$temp_file_ours"
  fi

  if [[ $(diff "$temp_file_theirs" "$temp_file_ours") ]]; then
    echo "Test failed. Diff output is below." | indent4 | in_red
    echo "'-' signs are next to your output." | indent4
    echo "'+' signs are next to the expected output." | indent4
    echo
    diff -u "$temp_file_theirs" "$temp_file_ours" | tail -n +4 | indent8
    fail_test "$test_name"
  else
    echo "Test passed." | indent4 | in_green
    ((++tests_passed))
    scores=$scores"\"$test_name\": 1"
  fi

  rm "$temp_file_theirs" "$temp_file_ours" 2> /dev/null
}

echo
check_solution flashlight flashlight.sh tests/flashlight.sol 1
scores="$scores, "
echo
check_solution "ghost-catcher-3000" "ghost-catcher-3000.sh" "tests/ghost-catcher-3000.sol" 1
scores="$scores, "
echo
check_solution "ghost-catcher-3001" "ghost-catcher-3001.sh" "tests/ghost-catcher-3001.sol" 1
scores="$scores, "
echo
check_solution find-the-hidden find-the-hidden.sh tests/find-the-hidden.sol 1
scores="$scores, "
echo
check_solution "ad-libs (bonus)" ad-libs.sh tests/ad-libs.sol 1

echo
echo "Finished."
echo "Tests passed: $tests_passed"
echo "Tests failed: $tests_failed"
echo "Tests total:" $((tests_failed + tests_passed))
echo
echo "{\"scores\": {$scores}}"
