#!/usr/bin/env bash

# This script checks your solution against our reference solution.
cd "$(dirname "$0")" || exit 1

scores=""

tests_passed=0
tests_failed=0
function no_trail_whitespace {
  sed -e 's/ *$//'
}

function check_solution {
  echo "Checking $1"
  local test_name=$1
  local theirs=$2
  local ours=$3
  temp_file=$(mktemp)
  if [ "$(uname)" = "Darwin" ]; then
    while IFS="" read -r line; do echo "$line" | no_trail_whitespace | md5; done < "$theirs" > "$temp_file"
  else
    while IFS="" read -r line; do echo "$line" | no_trail_whitespace | md5sum | awk '{print $1}'; done < "$theirs" > "$temp_file"
  fi

  if [[ $(cmp "$temp_file" "$ours") ]]; then
    echo "Your solution is incorrect at at line: " "$(cmp "$temp_file" "$ours" | sed -n -e 's/^.*, line //p')"
    echo "If you can't tell why, submit to Autolab for more detailed feedback."
    ((++tests_failed))
    scores=$scores"\"$test_name\": 0"
  else
    echo "Your solution is correct"
    ((++tests_passed))
    scores=$scores"\"$test_name\": 1"
  fi
}

echo
check_solution big-league ../big-league.txt tests/big-league.txt
scores="$scores, "
echo
check_solution clean-up ../clean-up.txt tests/clean-up.txt
scores="$scores, "
echo
check_solution fire-him ../fire-him.txt tests/fire-him.txt
scores="$scores, "
echo
check_solution kill-bugs ../kill-bugs.txt tests/kill-bugs.txt
scores="$scores, "
echo
check_solution up-down-all-around ../up-down-all-around.txt tests/up-down-all-around.txt
scores="$scores, "
echo
check_solution sliding ../sliding.txt tests/sliding.txt
scores="$scores, "
echo
check_solution "reformat (challenge)" ../reformat.txt tests/reformat.txt

echo
echo "Finished."
echo "Tests passed: $tests_passed"
echo "Tests failed: $tests_failed"
echo "Tests total:" $((tests_failed + tests_passed))
echo
echo "{\"scores\": {$scores}}"
