#!/usr/bin/env bash

# cd into folder where the driver is located, or quit (defensive)
# http://stackoverflow.com/questions/3349105
cd "${0%/*}" || exit 1

echo "In: $(pwd)"

# Helper colors
cnone="$(echo -ne '\033[0m')"
cwhiteb="$(echo -ne '\033[1;37m')"
cred="$(echo -ne '\033[0;31m')"
cgreen="$(echo -ne '\033[0;32m')"

# Detects whether we can add colors or not
# http://stackoverflow.com/a/911213
in_white() {
  [ -t 1 ] && echo -n "$cwhiteb"
  cat -
  [ -t 1 ] && echo -n "$cnone"
}
in_red() {
  [ -t 1 ] && echo -n "$cred"
  cat -
  [ -t 1 ] && echo -n "$cnone"
}
in_green() {
  [ -t 1 ] && echo -n "$cgreen"
  cat -
  [ -t 1 ] && echo -n "$cnone"
}

check_existence() {
  local file="$1"
  if [ ! -f "$file" ]; then
    echo "    $file does not exist." | in_red
    return 1
  fi
}

check_nonempty() {
  local file="$1"
  if [ ! -s "$file" ]; then
    echo "    $file is empty." | in_red
    return 1
  fi
}

plans_bool=1

echo "Testing plans.txt..." | in_white

check_existence ../plans.txt
if [ $? -ne 0 ]; then
    plans_bool=0
fi

check_nonempty ../plans.txt
if [ $? -ne 0 ]; then
    plans_bool=0
fi

tests_passed=$((plans_bool))
tests_failed=$((1 - plans_bool))

echo
echo "Finished."
echo "Tests passed: $tests_passed"
echo "Tests failed: $tests_failed"
echo "Tests total:  $((tests_passed + tests_failed))"
echo
echo "{\"scores\": {\"plans\": $plans_bool}}"
