#!/usr/bin/env bash

ABS_PATH="$(perl -MCwd -le 'print Cwd::abs_path(shift)' "${BASH_SOURCE[0]}")"
LAB_DIR="$(dirname "$ABS_PATH")"
cd "$LAB_DIR" || exit

# shellcheck disable=1090
source "$LAB_DIR/driver/problems"

in_order

