#!/usr/bin/env bash

# This script checks your solution against our reference solution.
cd "$(dirname "$0")" || exit 1

scores=""

tests_passed=0
tests_failed=0
function no_trail_whitespace {
  sed -e 's/ *$//'
}

function check_solution {
  echo "Checking $1"
  local test_name=$1
  local theirs=$2
  local ours=$3
  temp_file=$(mktemp)
  if [ "$(uname)" = "Darwin" ]; then
    while IFS="" read -r line; do echo "$line" | no_trail_whitespace | md5; done < "$theirs" > "$temp_file"
  else
    while IFS="" read -r line; do echo "$line" | no_trail_whitespace | md5sum | awk '{print $1}'; done < "$theirs" > "$temp_file"
  fi

  cmp "$temp_file" "$ours" >/dev/null 2>&1
  exit_code=$?
  if [[ $(cmp "$temp_file" "$ours") ]]; then
    echo "Your solution is incorrect at at line: " "$(cmp "$temp_file" "$ours" | sed -n -e 's/^.*, line //p')"
    echo "If you can't tell why, submit to Autolab for more detailed feedback."
    ((++tests_failed))
    scores=$scores"\"$test_name\": 0"
  elif [ ! $exit_code -eq 0 ]; then
    line_count=$(wc -l "$temp_file" | awk '{print $1}')
    line_count_ours=$(wc -l "$ours" | awk '{print $1}')
    echo "Your solution is incorrect; it caused our autograder to error."
    echo "This is most commonly caused by differing line counts in our file and yours."
    echo "Your solution has $line_count lines but ours has $line_count_ours lines."
    ((++tests_failed))
    scores=$scores"\"$test_name\": 0"
  else
    echo "Your solution is correct"
    ((++tests_passed))
    scores=$scores"\"$test_name\": 1"
  fi
}

echo
check_solution find-replace ../find-replace.txt tests/find-replace.txt
scores="$scores, "
echo
check_solution fix-typos ../fix-typos.txt tests/fix-typos.txt
scores="$scores, "
echo
check_solution hedwig ../hedwig.txt tests/hedwig.txt
scores="$scores, "
echo
check_solution hogwarts ../hogwarts.txt tests/hogwarts.txt

echo
echo "Finished."
echo "Tests passed: $tests_passed"
echo "Tests failed: $tests_failed"
echo "Tests total:" $((tests_failed + tests_passed))
echo
echo "{\"scores\": {$scores}}"
